export const SIGNOUT = "SIGNOUT";

export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_SIGNIN_FULFILLED = "FETCH_SIGNIN_FULFILLED";
export const FETCH_SIGNIN_REJECTED = "FETCH_SIGNIN_REJECTED";
