export const FETCH_SIGNUP = "FETCH_SIGNUP";
export const FETCH_SIGNUP_FULFILLED = "FETCH_SIGNUP_FULFILLED";
export const FETCH_SIGNUP_REJECTED = "FETCH_SIGNUP_REJECTED";

export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_SIGNIN_FULFILLED = "FETCH_SIGNIN_FULFILLED";
export const FETCH_SIGNIN_REJECTED = "FETCH_SIGNIN_REJECTED";

export const FETCH_SIGNIN_ACTIVE = "FETCH_SIGNIN_ACTIVE";
export const FETCH_SIGNIN_ACTIVE_FULFILLED = "FETCH_SIGNIN_ACTIVE_FULFILLED";
export const FETCH_SIGNIN_ACTIVE_REJECTED = "FETCH_SIGNIN_ACTIVE_REJECTED";

export const SIGNOUT = "SIGNOUT";
export const SIGNOUT_FULFILLED = "SIGNOUT_FULFILLED";

export const FETCH_FIND_ID = "FETCH_FIND_ID";
export const FETCH_FIND_ID_FULFILLED = "FETCH_FIND_ID_FULFILLED";
export const FETCH_FIND_ID_REJECTED = "FETCH_FIND_ID_REJECTED";

export const FETCH_FIND_ID_CONFIRM = "FETCH_FIND_ID_CONFIRM";
export const FETCH_FIND_ID_CONFIRM_FULFILLED = "FETCH_FIND_ID_CONFIRM_FULFILLED";
export const FETCH_FIND_ID_CONFIRM_REJECTED = "FETCH_FIND_ID_CONFIRM_REJECTED";

export const FETCH_FIND_PASSWORD = "FETCH_FIND_PASSWORD";
export const FETCH_FIND_PASSWORD_FULFILLED = "FETCH_FIND_PASSWORD_FULFILLED";
export const FETCH_FIND_PASSWORD_REJECTED = "FETCH_FIND_PASSWORD_REJECTED";
